version: '2'

services:
  db:
      image: postgres:latest
      environment:
        - POSTGRES_DB=amazon_db
        - POSTGRES_USER=cy141
        - POSTGRES_PASSWORD=passw@rd!
      restart: always
      volumes:
            - data-volume:/var/lib/postgresql/data
  web-init:
      build: ./web-app
      command: /code/initserver.sh
      volumes:
        - ./web-app:/code
      depends_on:
        - db
  web:
      build: ./web-app
      user: nobody
      command: /code/runserver.sh
      volumes:
        - ./web-app:/code
      expose:
        - "8000"
      depends_on:
        - web-init
  nginx:
     image: nginx:latest
     ports:
       - "8000:8000"
     volumes:
       - ./nginx/config:/etc/nginx/conf.d
     depends_on:
       - web
  backend:
      build: ./Backend
      command: bash -c "./gradlew run"
      ports:
        - "7777:7777" 
        - "8888:8888" 
      depends_on:
        - web
volumes:
   data-volume:
