# Generated by Django 4.1.5 on 2023-04-23 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item',
            table='Item',
        ),
        migrations.AlterModelTable(
            name='order',
            table='Order',
        ),
        migrations.AlterModelTable(
            name='ordered_items',
            table='Ordered_Items',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='UserProfile',
        ),
        migrations.AlterModelTable(
            name='warehouse',
            table='WareHouse',
        ),
    ]
