# Generated by Django 4.1.5 on 2023-04-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='header_img',
            field=models.ImageField(blank='/media/images/default.png', null='/media/images/default.png', upload_to='images/'),
        ),
    ]
