# Generated by Django 4.1.5 on 2023-04-30 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_server', '0002_alter_item_header_img'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shoppingcartitem',
            unique_together=set(),
        ),
    ]
