# Generated by Django 4.1.6 on 2023-04-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_server', '0005_alter_item_table_alter_order_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='package_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ups_account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
